os:
    - linux

language: python
python:
    - 2.7
    - 3.7

install:
    - python setup.py install

script:
    - echo 268642 > /tmp/test.txt
    - nhentai --cookie "csrftoken=3c4Mzn4f6NAI1awFqfIh495G3pv5Wade9n63Kx03mkSac8c2QR5vRR4jCwVzb3OR; sessionid=m034e2dyyxgbl9s07hbzgfhvadbap2tk"
    - nhentai --search umaru
    - nhentai --id=152503,146134 -t 10 --output=/tmp/ --cbz
    - nhentai --tag lolicon --sorting popular
    - nhentai -F
    - nhentai --file /tmp/test.txt
    - nhentai --id=152503,146134 --gen-main --output=/tmp/
